### ISSUE TITLE
CustomFunctionDialog.cpp.obj  too many sections (43405)   File too big

### ISSUE THREAD

**Issue by xkungfu** [Ola-jed/CurvePlotter#2]
hello, I have tried some solutions from google, but all failed.

LOG:
[1/2 0.0/sec] Building CXX object CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj
FAILED: CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj 
I:\CXXTools\Qt\Tools\mingw810_64\bin\g++.exe -DQT_CHARTS_LIB -DQT_CORE_LIB -DQT_EGL_SUPPORT_LIB -DQT_EVENTDISPATCHER_SUPPORT_LIB -DQT_FONTDATABASE_SUPPORT_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_ZLIB_LIB -II:/CXXProject/test/qtcharts_ola-jedCurvePlotter/build-CurvePlotter-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/CurvePlotter_autogen/include -II:/CXXProject/test/qtcharts_ola-jedCurvePlotter/CurvePlotter/include -II:/CXXProject/test/qtcharts_ola-jedCurvePlotter/CurvePlotter/lib -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtCore -isystem I:/CXXTools/Qt/5.15.2/wasm_32/./mkspecs/wasm-emscripten -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtGui -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtZlib -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtEventDispatcherSupport -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtFontDatabaseSupport -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtEglSupport -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtWidgets -isystem I:/CXXTools/Qt/5.15.2/wasm_32/include/QtCharts -flto -Wl,-allow-multiple-definition -g -std=gnu++2a -MD -MT CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj -MF CMakeFiles\CurvePlotter.dir\src\CustomFunctionDialog.cpp.obj.d -o CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj -c I:/CXXProject/test/qtcharts_ola-jedCurvePlotter/CurvePlotter/src/CustomFunctionDialog.cpp
I:/CXXTools/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj: too many sections (43405)
C:\Users\jhon\AppData\Local\Temp\ccOEvJVh.s: Assembler messages:
C:\Users\jhon\AppData\Local\Temp\ccOEvJVh.s: Fatal error: can't write 3923 bytes to section .gnu.lto_.inline.e237f32f of CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj: 'File too big'
I:/CXXTools/Qt/Tools/mingw810_64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj: too many sections (43405)
C:\Users\jhon\AppData\Local\Temp\ccOEvJVh.s: Fatal error: can't close CMakeFiles/CurvePlotter.dir/src/CustomFunctionDialog.cpp.obj: File too big
ninja: build stopped: subcommand failed.
10:53:39: Process "I:\CXXTools\Qt\Tools\CMake_64\bin\cmake.exe" exit，exit code 1 。
Error while building/deploying project CurvePlotter (kit: Desktop Qt 5.15.2 MinGW 64-bit)
When executing step "Build"

**Comment by Ola-jed** [comment]
Hello. I don't have Qt installed on windows, so I won't be able to build.
This error is happening because of the `exprtk.hpp` file which is heavy.
You can try adding one/all of those flags to the compiler `-Wa -mbig-obj`,`-flto -Wl`.
Thanks

**Comment by xkungfu** [comment]
thank you, I will have a test later and report the result.

**Comment by xkungfu** [comment]
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall") 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3" )  
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wa,-mbig-obj")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-long-long")

```
After I set some options above, the error "File too big" disappeared. But the compiler failed for another error. I will submit a new issue!

**Comment by xkungfu** [comment]
someone said they resolved via adding  "-Wa,-mbig-obj".
others said they still failed.
and I failed too.
based on my investigate, the only way on windows maybe reduce size of object file.

**Comment by Ola-jed** [comment]
Sorry for the silence. I don't know if you solved the problem but I recently tried to compile under windows and I got the same error but the flag `-Wa,-mbig-obj` which solved the problem. (It is now in the CMakeLists.txt file)
